images:
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.39.0"
- name: machine-controller-manager-provider-kubevirt
  sourceRepository: github.com/gardener/machine-controller-manager-provider-kubevirt
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-kubevirt
  tag: "v0.2.0"
- name: cloud-controller-manager
  sourceRepository: github.com/kubevirt/cloud-provider-kubevirt
  repository: eu.gcr.io/gardener-project/kubevirt-cloud-controller-manager
  tag: "v0.0.8"
