machineClasses:
- name: class-1
  storageClassName: standard
  pvcSize: "10Gi"
  sourceURL: source-image-url
  cpus: "1"
  memory: "4096M"
  sshKeys:
  - "ssh-rsa AAAAB3..."
  tags:
  - kubernetes.io/cluster/foo
  - kubernetes.io/role/node
  secret:
    cloudConfig: abc
    kubeconfig: abc
